### ISSUE TITLE
Can't import venn.py

### ISSUE THREAD

**Issue by tomasflyo** [tctianchi/pyvenn#15]
Hi,

After cloning the git and trying to import venn.py, I get the following error message:
`-bash: cd: source: No such file or directory
(lsl) [tomasfly@access2 pyvenn]$ import threading
Traceback (most recent call last):
  File "/apps/RH7U2/gnu/python/3.6.0/bin/import", line 11, in <module>
    load_entry_point('import==0.1.0', 'console_scripts', 'import')()
  File "/apps/RH7U2/gnu/python/3.6.0/lib/python3.6/site-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/apps/RH7U2/gnu/python/3.6.0/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/apps/RH7U2/gnu/python/3.6.0/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2408, in load
    return self.resolve()
  File "/apps/RH7U2/gnu/python/3.6.0/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2414, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/apps/RH7U2/gnu/python/3.6.0/lib/python3.6/site-packages/import.py", line 3
    print('This is ultran00b's package - import')
                             ^
SyntaxError: invalid syntax
`

any advice?

Thanks

**Comment by tctianchi** [comment]
Please run `ls -l` from your working directory. So that we can see your project structure.
